#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: rundeck-admin:schedule-takeover: "Claim all scheduled jobs from another cluster server."
#/ usage: rerun rundeck-admin:schedule-takeover  --uuid <>  --user <>  --url <>  --password <> 

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh schedule-takeover || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: rundeck-admin:schedule-takeover. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: UUID USER URL PASSWORD

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------

# Authenticate.
# --------------
rundeck_login $URL $USER $PASSWORD

# Takeover schedule.
# -------------------

CURL_OUT=$(mktemp "/tmp/curl.out.XXXXX")

# See http://rundeck.org/docs/api/index.html#takeover-schedule-in-cluster-mode
APIURL="${URL}/api/7/incubator/jobs/takeoverSchedule"

if ! rundeck_curl -H "Content-Type: application/xml" \
    --data "<server uuid=\"$UUID\"/>" -X PUT $APIURL > $CURL_OUT
then
    rerun_die 3 "API error: $APIURL"
fi

xmlstarlet val -q $CURL_OUT

if ! xmlstarlet sel -T -t -v "/result/@success" $CURL_OUT >/dev/null
then
    printf >&2 "API error: $APIURL"
    xmlstarlet sel -T -t -m "/result/error/message" -v "."  $CURL_OUT
    exit 1
fi

# Success/failure counters about schedule takeovers.
declare -i successful failed
successful=$(xmlstarlet sel -t -m "/result/takeoverSchedule/jobs/successful" -v @count $CURL_OUT)
failed=$(xmlstarlet sel -t -m "/result/takeoverSchedule/jobs/failed" -v @count $CURL_OUT)

# Print out the job IDs for the successfully taken over.
if [ "$successful" -gt 0 ] 
then
    xmlstarlet sel -t -m "/result/takeoverSchedule/jobs/successful/job" -v @id -n $CURL_OUT
fi

# Bail out but print the job IDs for the failed ones.
if [ "$failed" -ne 0 ]
then
    failed_ids=$(xmlstarlet sel -t -m "/result/takeoverSchedule/jobs/failed/job" -v @id -n $CURL_OUT)
    rerun_die 3 "Not all jobs taken over: $failed out of $((successful+failed)). jobs: $failed_ids"
fi

rm $CURL_OUT
# Done. Exit with last command exit status.
exit $?

