#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: rundeck-archive:apitoken-create: "Create an API token."
#/ usage: rerun rundeck-archive:apitoken-create  --password <>  --url <>  --user <> 

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh apitoken-create || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: rundeck-archive:apitoken-create. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: PASSWORD URL USER

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------

CURLOPTS="-f -s -S -L -c cookies -b cookies"
CURL="curl $CURLOPTS"
    
CURLOUT=$(mktemp -t curl.out.XXXXXXXXXX)

# Authenticate.
loginurl="${URL}/j_security_check"
$CURL $loginurl > /dev/null
$CURL -X POST -d j_username=$USER -d j_password=$PASSWORD $loginurl > /dev/null

# Request a new token.
tokenurl="$URL/user/generateApiToken"
$CURL $tokenurl?login=${USER} > $CURLOUT
xmlstarlet fo -R -H $CURLOUT > $CURLOUT.userprofile 2>/dev/null

# Check the result from the user profile.
# Tokens are printed in the order they were created.
tokens=( $(xmlstarlet sel -N x="http://www.w3.org/1999/xhtml" -t -m "//x:span[@class='apitoken']" -v . -n $CURLOUT.userprofile) )
[ -z "${tokens:-}" -a ${#tokens[*]} -lt 1 ] && {
    rerun_die "Failed to generate a token."
}


# Print token. It was the last created token.
echo ${tokens[${#tokens[*]} -1]}

# Clean up.
rm $CURLOUT $CURLOUT.userprofile

# Done. Exit with last command exit status.
exit $?

