# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Fri Jun 14 10:45:38 PDT 2013
#
#/ usage: rundeck-admin:jobs-archive [ --dir <>] [ --archive <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --dir) rerun_option_check $# $1; DIR=$2 ; shift ;;
            --archive) rerun_option_check $# $1; ARCHIVE=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.

    # Check required options are set

    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
DIR=
ARCHIVE=


