.TH rundeck-admin 1 "Wed Jun 26 07:21:51 PDT 2013" "Version 1.2.1" "RERUN User Manual" 
.SH NAME
rundeck-admin \- commands to manage your rundecks
.PP
.SH SYNOPSIS
.PP
\f[CR] 
rerun [ARGS] rundeck-admin: [ apitoken-create | apitoken-list | apitoken-remove | jobs-archive | project-create | project-export | project-import | project-list | project-remove | project-replicate | resource-add | resource-get | schedule-takeover | ssh-copy-id ] [OPTIONS]
\f[]

.SH COMMANDS
.SH rundeck-admin:apitoken-create \f[]--password <> --url <> --user <>

Create an API token.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:apitoken-list \f[]--password <> --url <> --user <>

List the API tokens.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:apitoken-remove \f[]--user <> --password <> --token <> --url <>

remove an api token
.PP
\f[I]OPTIONS\f[]
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--token \f[]the login token.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:jobs-archive \f[][--dir <>] [--archive <>]

Archive job files suitable for project import.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--dir \f[]directory path\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--archive \f[]the archive file.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-create \f[]--project <> --url <> --user <> --password <>

Create a project.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-export \f[]--project <> --url <> --user <> --password <> [--archive <>]

Export a project.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--archive \f[]the archive file.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-import \f[]--project <> --url <> --user <> --password <> [--archive <>]

Import a project archive.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--archive \f[]the archive file.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-list \f[]--url <> --user <> --password <>

List the projects.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-remove \f[]--project <> --url <> --user <> --password <>

Remove a project.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-replicate \f[]--url <> --to-url <> --project <> --user <> --password <>

Replicate the project(s) from one rundeck to another.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--to-url \f[]target rundeck instance.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:resource-add \f[]--user <> --password <> --url <> --project <> --model <>

add a resource to a project resource model.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--model \f[]the resource model.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:resource-get \f[]--user <> --password <> --url <> --resource <> --project <> [--format <>] [--file <>]

get resource info.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--resource \f[]the resource name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--format \f[]the file format.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--file \f[]file to store result.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:schedule-takeover \f[]--uuid <> --user <> --url <> --password <>

Claim all scheduled jobs from another cluster server.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--uuid \f[]the cluster server uuid.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:ssh-copy-id \f[]--user <> --password <> --keyfile <> --hostname <>

Copy an SSH key to another server.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--keypath \f[]path to ssh key file.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--hostname \f[]the server hostname.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE ; # command section done.

.SH RETURN VALUES
.PP
Successful completion: 0
.SH AUTHORS
alexh
.SH "SEE ALSO"
rerun
.SH KEYWORDS
rundeck-admin
