.TH rundeck-admin 1 "Wed May 14 15:58:11 PDT 2014" "Version 1.4.0" "RERUN User Manual" 
.SH NAME
rundeck-admin \- commands to manage your rundecks
.PP
.SH SYNOPSIS
.PP
\f[CR] 
rerun [ARGS] rundeck-admin: [ jobs-archive | key-content | key-list | key-remove | key-upload | project-configure | project-create | project-export | project-import | project-info | project-list | project-remove | project-replicate | resource-add | resource-get | schedule-takeover | ssh-copy-id | token-create | token-list | token-remove ] [OPTIONS]
\f[]

.SH COMMANDS
.SH rundeck-admin:jobs-archive \f[][--dir <>] [--archive <>]

Archive job files suitable for project import.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--dir \f[]directory path\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--archive \f[]the archive file.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:key-content \f[]--keypath <> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> --url <$RUNDECK_URL>

Get the key data content.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--keypath \f[]path to key file.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:key-list \f[]--keypath <> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> --url <$RUNDECK_URL>

List the key paths in the store.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--keypath \f[]path to key file.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:key-remove \f[]--keypath <> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> --url <$RUNDECK_URL>

Remove a key from the store.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--keypath \f[]path to key file.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:key-upload \f[][--file <>] --keypath <> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> --url <$RUNDECK_URL> [--format <>]

Upload key data and store it in the path.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--file \f[]file to store result.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--keypath \f[]path to key file.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--format \f[]the file format.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-configure \f[]--project <> --url <$RUNDECK_URL> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> [--file <>] [--format <>]

Configure a project.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--file \f[]file to store result.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--format \f[]the file format.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-create \f[]--project <> --url <$RUNDECK_URL> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD>

Create a project.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-export \f[]--project <> --url <$RUNDECK_URL> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> [--archive <>]

Export a project.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--archive \f[]the archive file.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-import \f[]--project <> --url <$RUNDECK_URL> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> [--archive <>] [--retain-uuids <true>] [--import-executions <true>]

Import a project archive.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--archive \f[]the archive file.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--retain-uuids \f[]Create Jobs with their defined UUIDs or a new UUID will be generated for each Job created.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]true\f[]
.RS
.RE
.TP
.B \--import-executions \f[]Creates new Executions and History reports from the archive.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-info \f[]--project <> --url <$RUNDECK_URL> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> [--format <>]

Get info about a project.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--format \f[]the file format.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-list \f[]--url <$RUNDECK_URL> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD>

List the projects.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-remove \f[]--project <> --url <$RUNDECK_URL> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD>

Remove a project.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:project-replicate \f[]--url <$RUNDECK_URL> --to-url <> --project <> --user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD>

Replicate the project(s) from one rundeck to another.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--to-url \f[]target rundeck instance.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:resource-add \f[]--user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> --url <$RUNDECK_URL> --project <> --model <>

Add a resource to a project resource model.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--model \f[]the resource model.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:resource-get \f[]--user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> --url <$RUNDECK_URL> --resource <> --project <> [--format <>] [--file <>]

Get resource info.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--resource \f[]the resource name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--project \f[]the project name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--format \f[]the file format.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--file \f[]file to store result.\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:schedule-takeover \f[]--uuid <> --user <$RUNDECK_USER> --url <$RUNDECK_URL> --password <$RUNDECK_PASSWORD>

Claim all scheduled jobs from another cluster server.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--uuid \f[]the cluster server uuid.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:ssh-copy-id \f[]--user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> --keypath <> --hostname <>

Copy an SSH key to another server.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--keypath \f[]path to key file.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--hostname \f[]the server hostname.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:token-create \f[]--password <$RUNDECK_PASSWORD> --url <$RUNDECK_URL> --user <$RUNDECK_USER>

Create an API token.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:token-list \f[]--password <$RUNDECK_PASSWORD> --url <$RUNDECK_URL> --user <$RUNDECK_USER>

List the API tokens.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-admin:token-remove \f[]--user <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> --token <> --url <$RUNDECK_URL>

Remove an api token.
.PP
\f[I]OPTIONS\f[]
.TP
.B \--user \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--token \f[]the login token.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE ; # command section done.

.SH RETURN VALUES
.PP
Successful completion: 0
.SH AUTHORS
alexh
.SH "SEE ALSO"
rerun
.SH KEYWORDS
rundeck-admin
